import fs from "fs"

const topics = JSON.parse(
fs.readFileSync("data/blog-topics.json","utf8")
)

const folder="assets/images"

if(!fs.existsSync(folder)){
fs.mkdirSync(folder,{recursive:true})
}

topics.forEach(topic=>{

const slug = topic
.toLowerCase()
.replace(/[^a-z0-9\s]/g,"")
.replace(/\s+/g,"-")

const meta={
title:topic,
description:`Illustration for ${topic}`,
subject:topic,
tags:[topic,"developer tools","online tools"],
author:"StartKnowledge",
copyright:"StartKnowledge",
rating:"General",
comments:"Generated by SEO automation engine"
}

let svg = `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
<rect width="1200" height="630" fill="#0d6efd"/>
<text 
x="50%" 
y="50%" 
dominant-baseline="middle" 
text-anchor="middle"
font-size="60"
fill="white"
font-family="Arial"
>
${topic}
</text>
</svg>
`
fs.writeFileSync(
`${folder}/${slug}.json`,
JSON.stringify(meta,null,2)
)

fs.writeFileSync(`${folder}/${slug}.svg`,svg)

})

console.log("Images generated")